### ISSUE TITLE
owl carousel 2.2.1 throws error ' $(...).owlCarousel is not a function ' with JQuery 3.3.1

### ISSUE THREAD

**Issue by JoshuaNeel** [OwlCarousel2/OwlCarousel2#2588]
I have used JQuery v1.11.1 with some of my plugins (mScrollBar, Owl Carousel, etc).

When I am trying to upgrade my JQuery version with 3.3.1, I am getting the error with owl carousel and mCustomScrollbar

This error is happening with all the browsers. This is the version specific error.
The prior seen solutions were not helpful for my situation.

**Comment by mort3za** [comment]
In my case, it works on jQuery 3.3.1, but after upgrading to jQuery 3.4.1 throws the mentioned error.

**Comment by mort3za** [comment]
In my case, there was 2 version of jquery was included in the final generated code. Maybe you should use an alias for older version of jQuery to prevent conflict.
